#!/bin/bash

# Define the source and destination paths
SRC_DIR="python_executables"
DEST_FILE="src/python_utils.rs"
REQ_FILE="$SRC_DIR/requirements.txt"

# Start writing the Rust file
echo "// This file is automatically generated by update_python.sh" > $DEST_FILE
echo "// Do not edit manually" >> $DEST_FILE
echo "" >> $DEST_FILE

# Loop through all Python files in the source directory
for file in $SRC_DIR/*.py; do
  # Extract the base name of the file (without the directory and extension)
  base_name=$(basename "$file" .py)
  # Read the content of the file and store it in a Rust raw string
  content=$(cat "$file")
  # One-liner doc
  echo "/// Python script content for $base_name.py" >> $DEST_FILE
  echo "pub const ${base_name^^}_SCRIPT: &str = r#\"$content\"#;" >> $DEST_FILE
  echo "" >> $DEST_FILE
done

echo "Python scripts have been successfully stored in $DEST_FILE as Rust strings."

